#!/usr/bin/env python3
"""Split a validated KAM archive into a core, immutable components and offline full ZIP.

Only Python's standard library is needed. Re-run detached signing AFTER this step.
The embedded manifest, not a mutable latest/version endpoint, defines compatibility.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import os
from pathlib import Path, PurePosixPath
import re
import shutil
import stat
import tempfile
import zipfile

MANIFEST = "components.json"
HELPER = "bin/magicnet-components"
BOOTSTRAP = '''
# Component bootstrap: generated by scripts/package-components.py.
# Run before migration/permission/config code needs the managed executables.
unzip -o "$ZIPFILE" "components.json" "bin/magicnet-components" -d "$MODPATH" >&2 ||
  abort "! failed to extract component bootstrap"
chmod 0755 "$MODPATH/bin/magicnet-components" || abort "! component bootstrap is not executable"
"$MODPATH/bin/magicnet-components" \
  --archive "$ZIPFILE" --module-dir "$MODPATH" \
  --previous-dir "${MAGICNET_PREV_DIR:-/data/adb/modules/MagicNet}" ||
  abort "! component verification/update failed; installation stopped"
# End component bootstrap.
'''


def digest(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def clean_path(name: str) -> str:
    path = PurePosixPath(name)
    if (not name or name.startswith("/") or "\\" in name or
            any(part in ("", ".", "..") for part in name.split("/")) or
            any(ord(c) < 32 for c in name) or str(path) != name):
        raise ValueError(f"Unsafe archive path: {name!r}")
    return name


def component_for(name: str) -> str | None:
    if name.startswith("bin/") and name.count("/") == 1:
        return "bin-" + name[4:]
    for prefix, component in (("webroot/", "webui"),
                              (".config/sing-box/zashboard/", "zashboard"),
                              (".config/sing-box/rules/", "rules")):
        if name.startswith(prefix):
            return component
    return None


def zip_entry(name: str, data: bytes, mode: int = 0o644, symlink: bool = False):
    info = zipfile.ZipInfo(name, date_time=(1980, 1, 1, 0, 0, 0))
    info.create_system = 3
    info.compress_type = zipfile.ZIP_DEFLATED
    info.external_attr = ((stat.S_IFLNK if symlink else stat.S_IFREG) | mode) << 16
    return info, data


def write_zip(path: Path, entries: dict[str, tuple[zipfile.ZipInfo, bytes]]) -> None:
    with zipfile.ZipFile(path, "w", compression=zipfile.ZIP_DEFLATED, compresslevel=9) as out:
        for name in sorted(entries):
            info, data = entries[name]
            out.writestr(info, data)


def split(source: Path, helper: Path, output: Path, repository: str, arch: str) -> dict:
    if not re.fullmatch(r"[A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+", repository):
        raise ValueError("Expected an owner/repository slug")
    if arch not in ("arm64", "amd64"):
        raise ValueError("Unsupported architecture")
    scaffold, groups = {}, {}
    removed_bytes = 0
    with zipfile.ZipFile(source) as src:
        seen = set()
        for info in src.infolist():
            if info.is_dir():
                clean_path(info.filename.rstrip("/"))
                continue
            name = clean_path(info.filename)
            if name in seen:
                raise ValueError(f"Duplicate ZIP entry: {name}")
            seen.add(name)
            if name in (MANIFEST, HELPER) or "# Component bootstrap:" in (
                    src.read(info).decode("utf-8") if name == "customize.sh" else ""):
                raise ValueError("Input is already componentized; use the original KAM archive")
            # Download archives are build caches, not runtime data. Do not ship a
            # second compressed copy of yq/jq/dashboard beside their installed files.
            if name.startswith(".local/state/") and name.endswith((".asset", ".archive")):
                removed_bytes += info.file_size
                continue
            if ".git" in name.split("/"):
                raise ValueError("Input has not passed the archive sanitizer")
            mode = info.external_attr >> 16
            kind = stat.S_IFMT(mode)
            if kind not in (0, stat.S_IFREG, stat.S_IFLNK):
                raise ValueError(f"Unsupported ZIP entry type: {name}")
            data = src.read(info)  # CRC is checked, too.
            symlink = kind == stat.S_IFLNK
            if symlink:
                target = data.decode("utf-8")
                resolved = os.path.normpath(str(PurePosixPath(name).parent / target))
                if target.startswith("/") or resolved == ".." or resolved.startswith("../"):
                    raise ValueError(f"Escaping symbolic link: {name}")
            permissions = 0o755 if name.startswith("bin/") or mode & 0o111 else 0o644
            entry = zip_entry(name, data, permissions, symlink)
            component = component_for(name) if not symlink else None
            if component:
                if not re.fullmatch(r"[A-Za-z0-9_.-]+", component):
                    raise ValueError(f"Invalid component ID: {component}")
                groups.setdefault(component, {})[name] = entry
            else:
                scaffold[name] = entry
    for required in ("module.prop", "customize.sh", ".config/sing-box/config.json"):
        if required not in scaffold:
            raise ValueError(f"Missing core entry: {required}")
    for required in ("bin-sing-box", "bin-magicnet-cli", "bin-magicnet-mcp-server"):
        if required not in groups:
            raise ValueError(f"Missing runtime component: {required}")
    prop = dict(line.split("=", 1) for line in scaffold["module.prop"][1].decode().splitlines()
                if "=" in line and not line.startswith("#"))
    if prop.get("id") != "MagicNet" or not re.fullmatch(r"v\d+\.\d+\.\d+", prop.get("version", "")):
        raise ValueError("Invalid module identity/version")
    text = scaffold["customize.sh"][1].decode("utf-8")
    anchor = "import this\n"
    if text.count(anchor) != 1:
        raise ValueError("customize.sh bootstrap anchor changed; review integration")
    scaffold["customize.sh"] = zip_entry("customize.sh", text.replace(anchor, anchor + BOOTSTRAP).encode(), 0o755)
    scaffold[HELPER] = zip_entry(HELPER, helper.read_bytes(), 0o755)
    manifest = {"schema": 1, "module": "MagicNet", "version": prop["version"],
                "architecture": arch, "repository": repository, "components": []}
    output.mkdir(parents=True, exist_ok=True)
    with tempfile.TemporaryDirectory(prefix=".components-", dir=output) as tmp:
        stage = Path(tmp)
        for component, entries in sorted(groups.items()):
            files = [{"path": name, "sha256": digest(data), "size": len(data),
                      "mode": (info.external_attr >> 16) & 0o777}
                     for name, (info, data) in sorted(entries.items())]
            # Payload ZIPs have normalized timestamps/order/permissions. Their
            # identities do NOT contain the MagicNet release version.
            asset = stage / "payload.zip"
            write_zip(asset, entries)
            checksum = digest(asset.read_bytes())
            filename = f"MagicNet-component-{component}-{checksum}.zip"
            asset.rename(stage / filename)
            manifest["components"].append({"id": component, "sha256": checksum,
                                            "size": (stage / filename).stat().st_size,
                                            "asset": filename, "files": files})
        encoded = (json.dumps(manifest, ensure_ascii=False, indent=2) + "\n").encode()
        scaffold[MANIFEST] = zip_entry(MANIFEST, encoded)
        (stage / MANIFEST).write_bytes(encoded)
        write_zip(stage / "MagicNet-core.zip", scaffold)
        complete = dict(scaffold)
        for entries in groups.values():
            complete.update(entries)
        write_zip(stage / "MagicNet-full.zip", complete)
        # Preserve update.json and the generic downloader's existing asset name.
        shutil.copyfile(stage / "MagicNet-core.zip", stage / "MagicNet.zip")
        report = {"version": prop["version"], "removed_build_cache_bytes": removed_bytes,
                  "core_bytes": (stage / "MagicNet-core.zip").stat().st_size,
                  "full_bytes": (stage / "MagicNet-full.zip").stat().st_size,
                  "components": [{"id": c["id"], "bytes": c["size"], "sha256": c["sha256"]}
                                 for c in manifest["components"]]}
        (stage / "package-sizes.json").write_text(json.dumps(report, indent=2) + "\n")
        (stage / "SHA256SUMS").write_text("".join(
            f"{digest(p.read_bytes())}  {p.name}\n" for p in sorted(stage.iterdir()) if p.is_file()))
        # Assemble every output before replacing any existing input/output file.
        for path in stage.iterdir():
            os.replace(path, output / path.name)
    return manifest


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("source", type=Path)
    parser.add_argument("--helper", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--repository", default="LIghtJUNction/MagicNet")
    parser.add_argument("--arch", choices=("arm64", "amd64"), default="arm64")
    args = parser.parse_args()
    manifest = split(args.source, args.helper, args.output, args.repository, args.arch)
    print(f"Packaged {len(manifest['components'])} components for {manifest['version']}")


if __name__ == "__main__":
    main()
